name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17.0'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install
        working-directory: ./Develop

      - name: Run End-to-End Tests
        run: npm run test
        working-directory: ./Develop

      - name: Run Component Tests
        run: npm run test-component 
        working-directory: ./Develop